version: '3.7'
services:
  dev:
    build:
      context: .
      target: dev
    command: /bin/bash
    volumes:
      - .:/app
    ports:
      - "9192:9192"
    environment:
      - NETGEAR_EXPORTER_ADMIN_PASSWORD
    network_mode: "host"

  deploy:
    build:
      context: .
      target: deploy
    ports:
      - "9193:9192"
    command: /bin/bash
